name: Greeting data academy

on:
  push:
    branches-ignore: [main]

env:
  DAY_OF_WEEK: Thursday

jobs:
  greeting_job:
    runs-on: self-hosted
    env:
      GREETING: Hello
    steps:
      - name: "Say 'Hello Data Academy 9th edition, this is <today's weekday> 's first exercise! I'm <MY_NAME>!'"
        run: echo "$GREETING $ACADEMY_TYPE Academy 9th edition, this is $DAY_OF_WEEK's second exercise! I'm $GITHUB_ACTOR"
        env:
          ACADEMY_TYPE: Data

  week_job:
    runs-on: self-hosted
    needs: greeting_job
    env:
      WEEK_NUMBER: first 
      MONTH: april
    steps:
      - name: "Say what is the current week of the month"
        run: echo "We are on the $WEEK_NUMBER week of $MONTH."

  unit_tests_job:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: 
          pip install -r 02_devops_fundamentals/github_actions/diy_1/unit_tests/requirements.txt

      - name: Test with pytest
        run: 
          pytest 02_devops_fundamentals/github_actions/diy_1/unit_tests --cov


